Add SECURITY.md file
eiffel-community/.github pull request #15
Opened 2022-02-10 13:02 UTC by t-persson

### Applicable Issues
N/A; change done as a result of discussion at the [2022-02-10 TC meeting](https://hackmd.io/sL9z7MGwSCOGSCXeY27mFg?view#February-10-2022).

### Description of the Change
Move the SECURITY.md file from the Community repository to this repository so that one can get information about security notices in all repositories.

### Alternate Designs
We currently have this file in the community repository which is an alternate design. The TC, however, wants this notice to be in all repositories.

### Benefits
Easier to see the security policy of Eiffel community

### Possible Drawbacks
None that I can think of.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2022-02-10 13:14 UTC, magnusbaeck requested changes

2022-02-10 13:14 UTC, magnusbaeck commented on SECURITY.md
> +We as a community encourage researchers, users and contributors to report vulnerabilities and security related issues to the Eiffel community. All issues are thoroughly investigated by a community se
Side note: https://eiffel-community.github.io/security.html looks awful :-)

2022-02-10 13:14 UTC, magnusbaeck commented on SECURITY.md
> +To file a vulnerability report please send and e-mail to the private eiffel-community-security@googlegroups.com  list. The e-mail should list the security specific details as well as the [standard bu
ISSUE_TEMPLATE.md link 404s, change to https://github.com/eiffel-community/.github/blob/master/.github/ISSUE_TEMPLATE/general.md.

2022-02-10 16:40 UTC, m-linner-ericsson approved these changes

2022-02-10 18:51 UTC, magnusbaeck approved these changes

2022-02-11 07:50 UTC, e-backmark-ericsson approved these changes

2022-02-11 07:51 UTC, merged